Update GH actions scripts

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,32 +1,55 @@
-name: Build Mod
-on: push
+name: Build Status
+
+on:
+  push:
+    branches: [ '*' ]
+  pull_request:
+
+env:
+  JAVA_VERSION: 25
 
 jobs:
   build:
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-26.04-arm
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Set up Eclipse Temurin 21
-        uses: actions/setup-java@v4
+      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+      - name: Set up JDK ${{ env.JAVA_VERSION }}
+        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
         with:
-          distribution: temurin
-          java-version: 21
-          cache: 'gradle'
+          java-version: ${{ env.JAVA_VERSION }}
+          distribution: 'microsoft'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
       - name: Build with Gradle
-        run: gradle build
+        run: gradle assemble
+      - name: Upload build artifacts (Common)
+        continue-on-error: true
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: ${{ github.event.repository.name }}-common-${{ github.sha }}
+          path: |
+            mod_common/build/libs/*.jar
       - name: Upload build artifacts (Fabric)
-        uses: actions/upload-artifact@v4
+        continue-on-error: true
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
-          name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
+          name: ${{ github.event.repository.name }}-fabric-${{ github.sha }}
           path: |
-            fabric/build/libs/*.jar
-            !fabric/build/libs/*-dev.jar
+            mod_fabric/build/libs/*.jar
       - name: Upload build artifacts (Neo)
-        uses: actions/upload-artifact@v4
+        continue-on-error: true
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
-          name: ${{ github.event.repository.name }}-Neo-${{ github.sha }}
+          name: ${{ github.event.repository.name }}-neo-${{ github.sha }}
           path: |
-            norge/build/libs/*.jar
-            !norge/build/libs/*-dev.jar
+            mod_neo/build/libs/*.jar
+      - name: Run tests
+        run: ./gradlew check
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v6.4.2
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
